name: cpr_assist
description: "A Flutter app for CPR assistance with real-time feedback and BLE integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4

  # Icons
  cupertino_icons: ^1.0.8

  # Logging
  logger: ^2.5.0

  # For BLE communication
  flutter_reactive_ble: ^5.0.2
  flutter_blue_plus: ^1.34.4
  permission_handler: ^11.3.1

  # For NFC Card
  url_launcher: ^6.1.7

  # For in-app browser
  webview_flutter: ^4.4.2

  share_plus: ^7.2.2
  qr_flutter: ^4.1.0

  # For location services
  geolocator: ^13.0.2
  google_maps_flutter: ^2.2.8
  google_maps_flutter_platform_interface: ^2.2.0
  google_maps_flutter_android: ^2.16.1
  flutter_compass: ^0.8.1

  # For proper connectivity checking
  connectivity_plus: ^4.0.2

  #For state management - Riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # For AES decryption
  encrypt: ^5.0.0

  # For icons
  flutter_svg: ^2.0.7

  # DateFormat
  intl: ^0.20.1
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.2.1

  # Fonts
  google_fonts: ^6.1.0

  #Keep screen awake
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.7

dependency_overrides:
  flutter_blue_plus_android: 4.0.2

flutter:
  uses-material-design: true

  # FONTS CONFIGURATION
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600

  # ASSETS CONFIGURATION
  assets:
    - .env
    - assets/map_style.json
    - assets/data/parsed_availability_map.json
    - assets/icons/AEDs.png
    - assets/icons/AEDs_c.png
    - assets/icons/kids_save_lives_logo.png
    - assets/icons/phone_call.svg
    - assets/icons/compass.svg
    - assets/icons/logo.svg
    - assets/icons/account.svg
    - assets/icons/bluetooth_on.svg
    - assets/icons/bluetooth_off.svg
    - assets/icons/bluetooth_search.svg
    - assets/icons/bluetooth_retry.svg
    - assets/icons/battery_100.svg
    - assets/icons/battery_70.svg
    - assets/icons/battery_50.svg
    - assets/icons/battery_30.svg
    - assets/icons/battery_1.svg
    - assets/icons/battery_charging.svg
    - assets/icons/locations.svg
    - assets/icons/live.svg
    - assets/icons/training.svg
    - assets/icons/frequency_arc.svg
    - assets/icons/frequency_arrow.svg
    - assets/icons/depth.svg
    - assets/icons/depth_line.svg
    - assets/icons/depth_circle.svg
    - assets/icons/depth_background.svg